# ===============================
# DATABASE CONFIG (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/hotel_booking_db
spring.datasource.username=postgres
spring.datasource.password=postgres123

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE CONFIG
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# show SQL queries in console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SERVER CONFIG
# ===============================
server.port=8080

# ===============================
# LOGGING (optional)
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ===============================
# JWT CONFIG
# ===============================
jwt.secret=your-very-secure-and-very-long-256-bit-secret-key-here-123456
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui